# Redis Configuration
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
#  datasource:
#    url: jdbc:mysql://<host>:<port>/<db_name>
#    username: <username>
#    password: <password>

# Server Configuration
server:
  port: 8080

